CREATE TABLE gomoku_games (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    room_code VARCHAR(8) NOT NULL,
    black_player_id BIGINT NOT NULL,
    white_player_id BIGINT DEFAULT NULL,
    current_player_id BIGINT NOT NULL,
    winner_id BIGINT DEFAULT NULL,
    board_json TEXT NOT NULL,
    move_count INT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'WAITING',
    finish_reason VARCHAR(20) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at DATETIME DEFAULT NULL,
    completed_at DATETIME DEFAULT NULL,
    UNIQUE KEY uk_gomoku_room_code (room_code),
    INDEX idx_gomoku_black_player (black_player_id),
    INDEX idx_gomoku_white_player (white_player_id),
    INDEX idx_gomoku_status (status),
    FOREIGN KEY (black_player_id) REFERENCES users(id),
    FOREIGN KEY (white_player_id) REFERENCES users(id),
    FOREIGN KEY (current_player_id) REFERENCES users(id),
    FOREIGN KEY (winner_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE chinese_chess_games (
     id BIGINT AUTO_INCREMENT PRIMARY KEY,
     room_code VARCHAR(8) NOT NULL,
     red_player_id BIGINT NOT NULL,
     black_player_id BIGINT DEFAULT NULL,
     current_player_id BIGINT NOT NULL,
     winner_id BIGINT DEFAULT NULL,
     board_json TEXT NOT NULL,
     move_count INT NOT NULL DEFAULT 0,
     last_from_row INT DEFAULT NULL,
     last_from_col INT DEFAULT NULL,
     last_to_row INT DEFAULT NULL,
     last_to_col INT DEFAULT NULL,
     status VARCHAR(20) NOT NULL DEFAULT 'WAITING',
     finish_reason VARCHAR(20) DEFAULT NULL,
     created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
     started_at DATETIME DEFAULT NULL,
     completed_at DATETIME DEFAULT NULL,
     UNIQUE KEY uk_chess_room_code (room_code),
     INDEX idx_chess_red_player (red_player_id),
     INDEX idx_chess_black_player (black_player_id),
     INDEX idx_chess_status (status),
     FOREIGN KEY (red_player_id) REFERENCES users(id),
     FOREIGN KEY (black_player_id) REFERENCES users(id),
     FOREIGN KEY (current_player_id) REFERENCES users(id),
     FOREIGN KEY (winner_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
